# Generated by Django 3.2.6 on 2021-08-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='usuario')),
                ('is_staff', models.BooleanField()),
                ('is_superuser', models.BooleanField()),
                ('pais', models.CharField(choices=[('0', 'chile'), ('1', 'mexico'), ('2', 'salvador'), ('3', 'peru')], max_length=1, verbose_name='pais')),
                ('genero', models.CharField(choices=[('m', 'mujer'), ('h', 'hombre')], max_length=1, verbose_name='genero')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
