# Generated by Django 3.2.6 on 2021-08-15 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=50, verbose_name='Ingresa tu pregunta')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha creacion')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField()),
                ('votos', models.IntegerField(default=0)),
                ('preg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.preguntas')),
            ],
        ),
    ]
