# Generated by Django 3.2.6 on 2021-08-27 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_respuesta_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='preg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas_respuestas', to='home.preguntas'),
        ),
    ]
