# Generated by Django 3.2.6 on 2021-08-30 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_respuesta_preg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
