# Generated by Django 3.2.6 on 2021-08-30 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_respuesta_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respuesta',
            old_name='respuesta',
            new_name='respu',
        ),
    ]
