# Generated by Django 3.2.6 on 2021-08-30 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_respuesta_respuesta_respu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respuesta',
            old_name='respu',
            new_name='respuesta',
        ),
    ]
