# Generated by Django 3.2.6 on 2021-08-30 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_respu_respuesta_respuesta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preguntas',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='preguntas',
            name='name',
        ),
    ]
