# Generated by Django 3.2.6 on 2021-08-30 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_respuesta_votos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='votos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
